config/routes.rb
Rails.application.routes.draw do

  get 'merchantlogin', to: 'merchantsessions#new'
  post 'merchantlogin', to: 'merchantsessions#create'
  delete 'logout', to: 'merchantsessions#destroy'

  get 'userlogin', to: 'usersessions#new'
  post 'userlogin', to: 'usersessions#create'
  delete 'logout', to: 'usersessions#destroy'

  resources :merchants
  resources :users
  resources :products
  resources :users do
    member do
      get 'receipt', to: 'users#show_receipt'
    end
  end
  resources :orders, only: [:new, :create, :show, :index]
  resources :payments, only: [:new, :create, :show]
  resources :transactions, only: [:index, :show]

  root 'top#main'
  
  get 'get_image/:id', to: 'products#get_image'
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        
    end
end

app/views/top/login.html.slim
h1 Log in
= form_tag '/top/login' , method: :post do
    = label_tag :user_name, '名前'
    = text_field_tag :user_name
    .submit
        = submit_tag 'ログイン'
    .new_user
        = link_to '新規登録の方はこちら', new_user_path

= link_to 'お店の方はこちら', '/login'

app/views/top/main.html.slim
.row
    = link_to 'ユーザーログイン', "/userlogin", class: 'btn btn-block btn-outline-primary btn-sm'

.row
    = link_to 'お店の方のログイン', "/merchantlogin", class: 'btn btn-block btn-outline-primary btn-sm'

app/views/top/shoplogin.html.slim
h1 Log in
= form_tag '/top/shoplogin' , method: :post do
    = label_tag :merchant_name, '名前'
    = text_field_tag :merchant_name
    .submit
        = submit_tag 'ログイン'
    .new_merchant
        = link_to '新規登録の方はこちら', new_merchant_path