config/routes.rb
Rails.application.routes.draw do

  get 'merchantlogin', to: 'merchantsessions#new'
  post 'merchantlogin', to: 'merchantsessions#create'
  delete 'logout', to: 'merchantsessions#destroy'

  get 'userlogin', to: 'usersessions#new'
  post 'userlogin', to: 'usersessions#create'
  delete 'logout', to: 'usersessions#destroy'

  resources :merchants
  resources :users
  resources :products
  resources :users do
    member do
      get 'receipt', to: 'users#show_receipt'
    end
  end
  resources :orders, only: [:new, :create, :show, :index]
  resources :payments, only: [:new, :create, :show]
  resources :transactions, only: [:index, :show]

  root 'top#main'
  
  get 'get_image/:id', to: 'products#get_image'
end

app/models/merchant.rb
class Merchant < ApplicationRecord
    has_many :products, dependent: :destroy
    has_many :orders, dependent: :destroy
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
    def index
        @merchants = Merchant.all
    end
    def new
        @merchant = Merchant.new
    end
    
    def create
        @merchant = Merchant.new(merchant_params)
        if @merchant.save!
            flash[:notice] = "登録が完了しました"
            redirect_to "/merchantlogin"
        else
            render new_merchant_path
        end
    end

    def show
        @merchant = Merchant.find(params[:id])
        @products = @merchant.products
        
    end

    private
    def merchant_params
        params.require(:merchant).permit(:merchant_name, :seller)
    end
end

app/views/merchants/index.html.slim
h1 お店一覧

- if user_logged_in?
    = link_to 'マイページ', user_path(current_user.id), class: 'btn btn-block btn-outline-primary btn-sm'

-@merchants.each_slice(4) do |slice_merchants|
    .row
        - slice_merchants.each do |merchant|
            .col-md-3
                .card.my-3
                    .card-body
                        h5.card-title
                            = merchant.merchant_name
                        .card-text
                            よく売ってるもの
                            = merchant.seller
                        .card-text
                            = link_to 'このお店に入る', merchant_path(merchant.id), class: 'btn btn-block btn-outline-primary btn-sm'

.logout
    = button_to 'Log out', logout_path, method: :delete

app/views/merchants/new.html.slim
h1 新規登録
= form_for @merchant, action: :create do |t|
  .form-group
    = t.label :merchant_name, '名前'
    = t.text_field :merchant_name
  .form-group
    = t.label :seller, 'よく売るもの'
    = t.text_field :seller
  = t.submit '登録'

app/views/merchants/show.html.slim
h3 商品一覧

- if merchant_logged_in?
    = link_to "新商品追加", new_product_path, class: 'btn btn-block btn-outline-primary btn-sm'

.col
    h5.mt-3
        = @merchant.merchant_name
        | のお店の商品
    - if @products.empty?
        | なし
    -@products.each_slice(4) do |slice_products|
        .row
            - slice_products.each do |product|
                .col-md-3
                    .card.my-3
                        = image_tag product.image, height: 200, style: "object-fit: cover"
                        .card-body
                            h5.card-title
                                = product.title
                            p.card-text
                                = product.description.truncate(35)
                            .card-text
                                = product.price
                            - if product.purchased_at.nil?
                                = link_to '購入', '/orders/new', class: 'btn btn-block btn-outline-primary btn-sm'
                            -else
                                .btn.btn-outline-secondary.btn-block.btn-sm.disabled 購入済み

= link_to '戻る', '/merchants', class: 'btn btn-block btn-outline-primary btn-sm'

.logout
= button_to 'Log out', logout_path, method: :delete